sequenceDiagram
    autonumber
    actor Client as Client
    participant P1 as PUT /backprocess/bff/deferall/{DeferralGuid}/update
    Client->>+P1: PUT /backprocess/bff/deferall/{DeferralGuid}/update
    P1-->>-Client: Results<Ok<UpdateDeferralInformationResponse>, ProblemDetails>
